using System.Security.Claims;

namespace Infrastructure.Authentication;

internal static class ClaimsPrincipalExtensions
{
    public static Guid GetUserId(this ClaimsPrincipal? principal)
    {
        var userId = principal?.FindFirstValue(ClaimTypes.NameIdentifier);

        return Guid.TryParse(userId, out var parsedUserId) ?
            parsedUserId :
            throw new ApplicationException("User id is unavailable");
    }
}


// eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5RmNWT3ZsQURXUmZucjM5WS1HVkMyaHA3X2R4UmVQaXU4Nnk2czI3Sk1vIn0.eyJleHAiOjE3NzgwNjcyNTMsImlhdCI6MTc3ODA2Njk1MywiYXV0aF90aW1lIjoxNzc4MDY2OTUyLCJqdGkiOiJvbnJ0YWM6MmYwOTU4ZjktOGI2Mi1iYTJkLWZmNTQtMDg0NDQxNGE2MjkyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9tb24tcmVhbG0iLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZWExZGEyOWItMmZhYi00OWMzLTkyMzQtNDBiNTU1MDQyNDRjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibW9uLWNsaWVudCIsInNpZCI6Il8xTzNxS3U5dGRNZlhzbDZWSG5NUTBuYyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiZGVmYXVsdC1yb2xlcy1tb24tcmVhbG0iLCJvZmZsaW5lX2FjY2VzcyIsImFkbWluIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiVGjDqW8gbGFmb3JnZSIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoiVGjDqW8iLCJmYW1pbHlfbmFtZSI6ImxhZm9yZ2UiLCJlbWFpbCI6InRoZW8ubGFmb3JnZTIxQGdtYWlsLmNvbSJ9.jfxKsbamBdbsAQUJVMywoppFOx3oeSDlA8wbbrvPCRpUNXnF7adlEuZJg5OgMAH0a6clfU3N-xH4VvPb6o2hqPP-bMFsPn48TawC0RCixOG38jL9x98NjsXMMuwrMGCocQ4DTuRZ_NR8wXStZH9wyfzWc_rIGZjGeK3M0-U1BXIJU2GfKfjGimaz-anr263sHPex9Tc0m85YWa9ydIEu3kzxCx9HUTTUmxxBddVktoEvhPVwChCu79-sajwyY3utLjLu4Xu4yToxBRaUrqc9aN3pMWGx2r8Z3VTmWbgPOD0MuHZR_olTEIr7L_fHCk2_vrJAeKjjB0VhXbiLW6M1qA
